# Generated by Django 4.2.7 on 2023-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.URLField(default='https://png.pngtree.com.jpg', verbose_name='Постер'),
        ),
    ]
