# Generated by Django 4.2.7 on 2023-12-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
