# Generated by Django 4.2.7 on 2023-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to='posters/', verbose_name='Постер'),
        ),
    ]
