# Generated by Django 4.2.7 on 2023-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.URLField(default='https://png.pngtree.com.jpg', verbose_name='Постер'),
        ),
    ]
