# Generated by Django 4.2.7 on 2023-12-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/base.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
